---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "DipNas dashboard"
subtitle: "Welcome"
# documentTitle: "Welcome" # Customize the browser tab text
logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/assets/logo.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: '<p>Created with <span class="has-text-danger"> d i p a k . .</i></a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
# You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level.

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
stylesheet:
  - "https://raw.githubusercontent.com/dipak003/diphome/main/resources/assets/themes/custom.css"

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media & Services"
    icon: "fa-solid fa-photo-film"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Synology Photos"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-photos.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
        subtitle: "Synology Photos"
        tag: "photos"
        keywords: "Synology Photos and memories" # optional keyword used for searching purpose
        url: "https://dipnas.local/photos/"
        target: "Photos" # optional html tag target attribute
      - name: "Jellyfin"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/jellyfin-white-logo.png"
        subtitle: "Jellyfin is media server and suite of multimedia applications"
        tag: "movies"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://dipnas.local:8096/web/index.html#!/home.html"
      - name: "Photoprism"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/photoprism-logo.png"
        subtitle: "PhotoPrism is an AI-Powered Photos App for the Decentralized Web"
        tag: "photos"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://dipnas.local:8082/library/albums"
      - name: "Photoprism2"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/photoprism-logo.png"
        subtitle: "PhotoPrism is an AI-Powered Photos App for the Decentralized Web"
        tag: "photos"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://dipnas.local:8083/library/albums"
      - name: "Audio station"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-audiostation.png"
        subtitle: "Synology audio station or music station"
        tag: "audio"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "https://dipnas.local/audio/"
  - name: "Application"
    icon: "fas fa-code-branch"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Synology DSM"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-dsm-icon.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
        subtitle: "Synology DiskStation Manager (DSM)"
        tag: "dsm"
        tagstyle: "is-primary"
        keywords: "self hosted reddit" # optional keyword used for searching purpose
        url: "http://dipnas.local/"
        target: "DSM" # optional html tag target attribute
      - name: "Synology Files"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-filestation.png"
        subtitle: "Synology File server"
        tag: "files"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "https://dipnas.local/files/"
      - name: "Synology Drive"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-drive.png"
        subtitle: "Synology Drive"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "https://dipnas.local/drive/"
      - name: "Download station"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-downloadstation.png"
        subtitle: "Synology download station"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "https://dipnas.local/download/"
  - name: "Administration"
    icon: "fa fa-cog fa-spin fa-1x fa-fw"
    items:
      - name: "Synology DSM"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-dsm-icon.png"
        # Alternatively a fa icon can be provided:
        #icon: "fab fa-jenkins"
        subtitle: "Synology DiskStation Manager (DSM)"
        tag: "dsm"
        tagstyle: "is-primary"
        keywords: "self hosted reddit" # optional keyword used for searching purpose
        url: "http://dipnas.local/"
        target: "DSM" # optional html tag target attribute
      - name: "Synology Active Backup"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/synology-active-backup-logo.png"
        subtitle: "Synology active backup for business"
        tag: "backup"
        tagstyle: "is-primary"
        keywords: "self hosted reddit" # optional keyword used for searching purpose
        url: "https://dipnas.local/activebackup/"
        target: "active backup" # optional html tag target attribute
      - name: "Portainer"
        logo: "https://raw.githubusercontent.com/dipak003/diphome/main/resources/icons/portainer-logo.png"
        # subtitle: "Network-wide Ad Blocking" # optional, if no subtitle is defined, PiHole statistics will be shown
        tag: "app"
        url: "https://dipnas.local:9443/#!/home"
        type: "Portainer" # optional, loads a specific component that provides extra features. MUST MATCH a file name (without file extension) available in `src/components/services`
        target: "Portainer" # optional html a tag target attribute
        # class: "green" # optional custom CSS class for card, useful with custom stylesheet
        # background: red # optional color for card to set color directly without custom stylesheet